Logistic Regression Using 3 PCA Components (Labels from KMeans on 3 PCA Components)

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, f1_score, precision_score, balanced_accuracy_score

In [55]:
features = pd.read_csv("pca_3.csv")
features = features.drop("Unnamed: 0", axis=1)

# labels obtained from KMeans on 3 PCA Features
labels = pd.read_csv("kmeans_pca_3.csv")
labels = labels.loc[:,"Labels"]

# split data into training and testing data (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2)

y_true = y_test.to_numpy()

In [69]:
# Fitting Model Using Training Data
clf = LogisticRegression().fit(X_train, y_train)

# Predicting Labels Using Test Data
y_pred = clf.predict(X_test)
print(y_true)
print(y_pred)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average="weighted")
f1 = f1_score(y_true, y_pred, average="weighted")
print("Accuracy: " + str(accuracy))
print("Precision: " + str(precision))
print("F1 Score / F-Score: " + str(f1))

[2 1 2 ... 0 1 0]
[2 1 2 ... 0 1 0]
Accuracy: 0.9988634015292416
Precision: 0.9988643578804127
F1 Score / F-Score: 0.9988634261847212


Running Logistic Regression Using 7 PCA Componenets (80% Variance) - Still Using KMeans w/ 3 PCA Components for Labels

In [57]:
features_pca80 = pd.read_csv("pca_80.csv")
features_pca80 = features_pca80.drop("Unnamed: 0", axis=1)

# labels obtained from KMeans on 3 PCA Features
labels = pd.read_csv("kmeans_pca_3.csv")
labels = labels.loc[:,"Labels"]

# split data into training and testing data (80% train, 20% test)
X_train2, X_test2, y_train2, y_test2 = train_test_split(features_pca80, labels, test_size=0.2)

y_true2 = y_test2.to_numpy()

In [65]:
# Fitting Model Using Training Data
clf = LogisticRegression().fit(X_train2, y_train2)

# Predicting Labels Using Test Data
y_pred2 = clf.predict(X_test2)
print(y_true2)
print(y_pred2)

accuracy = accuracy_score(y_true2, y_pred2)
precision = precision_score(y_true2, y_pred2, average="weighted")
f1 = f1_score(y_true2, y_pred2, average="weighted")
print("Accuracy: " + str(accuracy))
print("Precision: " + str(precision))
print("F1 Score / F-Score: " + str(f1))

[3 1 0 ... 0 1 1]
[3 1 0 ... 0 1 1]
Accuracy: 0.9989667286629469
Precision: 0.9989672228915609
F1 Score / F-Score: 0.9989667570952033
